### ISSUE TITLE
gradle的时候出现了一下问题

### ISSUE THREAD

**Issue by bzy601638015** [ohmerhe/Kolley#1]
Error:Could not find property 'BINTRAY_USER' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@43202a96.

**Comment by ohmerhe** [comment]
可以先 在 Library 的 gradle 文件 把这句 `apply from: 'bintray.gradle'` 注释掉。

**Comment by bzy601638015** [comment]
注释过后，重新编译提示了一下错误信息：
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.ohmerhe.kotlinthree:andex:0.1.9.
     Searched in the following locations:
         file:/Users/baozhiyuan/.m2/repository/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.pom
         file:/Users/baozhiyuan/.m2/repository/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.jar
         https://jcenter.bintray.com/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.pom
         https://jcenter.bintray.com/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.jar
         https://repo1.maven.org/maven2/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.pom
         https://repo1.maven.org/maven2/com/ohmerhe/kotlinthree/andex/0.1.9/andex-0.1.9.jar

**Comment by ohmerhe** [comment]
这是依赖库的问题，已经更新了
你可以再编译一下
