### ISSUE TITLE
往post body里面添加参数，怎样添加

### ISSUE THREAD

**Issue by guxiaonian** [ohmerhe/Kolley#4]

**Comment by ohmerhe** [comment]
可以直接加在params 上
也可以放在 raw 里面

**Comment by sjx19900424** [comment]
放在param里面




------------------ 原始邮件 ------------------
发件人: "ohmerhe";<notifications@github.com>;
发送时间: 2017年10月27日(星期五) 下午3:28
收件人: "ohmerhe/Kolley"<Kolley@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ohmerhe/Kolley] 往post body里面添加参数，怎样添加 (#4)




可以直接加在params 上
 也可以放在 raw 里面

**Comment by ohmerhe** [comment]
没有疑问的话，我把这个问题关了 @guxiaonian
