### ISSUE TITLE
0.3.1 build failed

### ISSUE THREAD

**Issue by hoobo0506** [ohmerhe/Kolley#8]
i was trying to use the lastest version 0.3.1 on Android Studio 3.0 , it failed with error below.`Failed to resolve: com.github.franmontiel:PersistentCookieJar:v1.0.1`
Please let me know if any solution for this.
And when I tried out 0.3.0, build falied with this issue below:
>Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by ohmerhe** [comment]
You must add the JitPack repository in your root build.gradle at the end of repositories as descript in [PersistentCookieJar](https://github.com/franmontiel/PersistentCookieJar) Project.
```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```
I will remind it in readme later.

**Comment by hoobo0506** [comment]
it works for me .Thank you very much !
